keycloak:
  resource: Progetto-piattaforme

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
  application:
    name: ProgettoPiattaforme

  datasource:
    password: base
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:

      ddl-auto: update
    properties:
      hibernate:
        default_schema: store

jwt:
  auth:
    converter:
      resource-id: progetto-rest-api
      principle-attribute: preferred_username

server:
  compression:
    enabled: 'true'
  port: '8081'




